function ret = pathMaker(params, N, L, background_g_noise, prefix, suffix)
    ret = sprintf('output/%s_m%dbg%dk%do%db%ds%dr%dN%dL%dGN%d%s', prefix, params.m, params.backgroundAmount, params.k, ...
                  params.order, params.doGTBound, params.doESharing, params.doResampling, N, L, ...
                  round(background_g_noise * 100), suffix);
end